In [1]:
import torch

In [7]:
x = torch.tensor([[1,2,3,4]])
print(x, x.shape)
print(x.dim())

tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
2


In [11]:
x = torch.tensor([[[1,2,3,4], 
                   [2,3,4,5], 
                   [2,3,4,6]], 

                  [[1,2,3,6], 
                   [2,3,4,5], 
                   [2,3,4,6]]])
print(x.shape)
print(x.dim())

torch.Size([2, 3, 4])
3


In [13]:
scalar = torch.tensor(2)
scalar, scalar.shape

(tensor(2), torch.Size([]))

In [17]:
# Batch processimg
batch_size = 3
sequence_length = 4
batch_sequences = torch.tensor([
    [10,20,30,40],
    [50,60,70,80],
    [90,10,20,30]
])

print(f'Batch of sequences: \n{batch_sequences} - Shape: {batch_sequences.shape}')

Batch of sequences: 
tensor([[10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 10, 20, 30]]) - Shape: torch.Size([3, 4])


In [24]:
feature_size = 2
batch_with_features = torch.tensor([
    [[[1.0,2.0], [3.0,4.0], [5.0,6.0], [7.0,8.0]],
     [[1.5,2.5], [3.5,4.5], [5.5,6.5], [7.5,8.5]],
     [[1.5,2.0], [3.0,4.5], [5.5,6.0], [7.0,8.5]]], 
     
    [[[1.0,2.0], [3.0,4.0], [5.0,6.0], [7.0,8.0]],
     [[1.5,2.5], [3.5,4.5], [5.5,6.5], [7.5,8.5]],
     [[1.5,2.0], [3.0,4.5], [5.5,6.0], [7.0,8.5]]], 
     
])
print(f'Batch of sequences with features: \n{batch_with_features} - Shape: {batch_with_features.shape}')

Batch of sequences with features: 
tensor([[[[1.0000, 2.0000],
          [3.0000, 4.0000],
          [5.0000, 6.0000],
          [7.0000, 8.0000]],

         [[1.5000, 2.5000],
          [3.5000, 4.5000],
          [5.5000, 6.5000],
          [7.5000, 8.5000]],

         [[1.5000, 2.0000],
          [3.0000, 4.5000],
          [5.5000, 6.0000],
          [7.0000, 8.5000]]],


        [[[1.0000, 2.0000],
          [3.0000, 4.0000],
          [5.0000, 6.0000],
          [7.0000, 8.0000]],

         [[1.5000, 2.5000],
          [3.5000, 4.5000],
          [5.5000, 6.5000],
          [7.5000, 8.5000]],

         [[1.5000, 2.0000],
          [3.0000, 4.5000],
          [5.5000, 6.0000],
          [7.0000, 8.5000]]]]) - Shape: torch.Size([2, 3, 4, 2])


In [26]:
original = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(f"{original}, Shape: {original.shape}")

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]), Shape: torch.Size([4, 3])


In [28]:
original.reshape((2,6)), original.reshape((6,2))

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [30]:
original.reshape(-1).tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [32]:
viewed = original.view(3,4)
viewed, viewed.shape


(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [33]:
viewed[0,0] = 10

In [34]:
viewed

tensor([[10,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [35]:
batch_sequences

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 10, 20, 30]])

In [36]:
batch_sequences[0]

tensor([10, 20, 30, 40])

In [37]:
batch_sequences[:, 0]

tensor([10, 50, 90])

In [38]:
batch_sequences[:, -1]

tensor([40, 80, 30])

In [39]:
singleton = torch.tensor([1,2,3])
print(singleton, singleton.shape)

tensor([1, 2, 3]) torch.Size([3])


In [44]:
singleton.dim()

1

In [51]:
data = torch.tensor([[1,2,3], [4,5,6]])
biases = torch.tensor([10,20,30])
print(data.shape, biases.shape)
data + biases

torch.Size([2, 3]) torch.Size([3])


tensor([[11, 22, 33],
        [14, 25, 36]])

In [54]:
# We have a vector of 3 values
biases = torch.tensor([10, 20, 30])  # Shape: [3]

# And a batch of 2 samples, each with 3 features
data = torch.tensor([[1, 2, 3], 
                     [4, 5, 6]])    # Shape: [2, 3]

# Direct addition fails!
result = data + biases  # ERROR: shapes don't match
result

tensor([[11, 22, 33],
        [14, 25, 36]])

In [67]:
col = torch.tensor([1,2,3])
row = torch.tensor([4,5])

print(row, col)
print(row.shape, col.shape)

tensor([4, 5]) tensor([1, 2, 3])
torch.Size([2]) torch.Size([3])
